# Generated by Django 3.2.12 on 2022-03-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, null=True)),
                ('content', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
