# Generated by Django 3.2.12 on 2022-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='content_two',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
