# Generated by Django 3.2.12 on 2022-03-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_content_two'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Enter',
        ),
    ]
